github.com:
    git_protocol: ssh
    users:
        P4X-ng:
            oauth_token: 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
    user: P4X-ng
    oauth_token: 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
