name = "pfs-vcpu"
main = "cloudflare-vcpu.js"
compatibility_date = "2024-01-01"
workers_dev = true

# Optional: custom domain
# routes = [
#   { pattern = "vcpu.yourdomain.com/*", zone_id = "YOUR_ZONE_ID" }
# ]

[env.production]
vars = { ENVIRONMENT = "production" }

# Optional: KV namespace for state
# [[kv_namespaces]]
# binding = "PACKET_STATE"
# id = "YOUR_KV_NAMESPACE_ID"