apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-web-app
  template:
    metadata:
      labels:
        app: nginx-web-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.20
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-web-app
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
